# First Test

In [ ]:
######

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('salaries_by_college_major.csv')

In [ ]:
df.head()

In [ ]:
df.shape

(51, 6)

In [ ]:
df.columns

Index(['Undergraduate Major', 'Starting Median Salary',
       'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
       'Mid-Career 90th Percentile Salary', 'Group'],
      dtype='object')

In [ ]:
df.isna()

In [ ]:
df.tail()

In [ ]:
clean_df = df.dropna()

In [ ]:
clean_df.tail()

In [ ]:
clean_df["Starting Median Salary"].max()

74300.0

In [ ]:
clean_df['Starting Median Salary'].idxmax()

43

In [ ]:
clean_df['Undergraduate Major'][43]

'Physician Assistant'

In [ ]:
clean_df

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business
5,Art History,35800.0,64900.0,28800.0,125000.0,HASS
6,Biology,38800.0,64800.0,36900.0,135000.0,STEM
7,Business Management,43000.0,72100.0,38800.0,147000.0,Business
8,Chemical Engineering,63200.0,107000.0,71900.0,194000.0,STEM
9,Chemistry,42600.0,79900.0,45300.0,148000.0,STEM
10,Civil Engineering,53900.0,90500.0,63400.0,148000.0,STEM
11,Communications,38100.0,70000.0,37500.0,143000.0,HASS
12,Computer Engineering,61400.0,105000.0,66100.0,162000.0,STEM
13,Computer Science,55900.0,95500.0,56000.0,154000.0,STEM
14,Construction,53700.0,88900.0,56300.0,171000.0,Business
15,Criminal Justice,35000.0,56300.0,32200.0,107000.0,HASS
16,Drama,35900.0,56900.0,36700.0,153000.0,HASS
17,Economics,50100.0,98600.0,50600.0,210000.0,Business
18,Education,34900.0,52000.0,29300.0,102000.0,HASS
19,Electrical Engineering,60900.0,103000.0,69300.0,168000.0,STEM
20,English,38000.0,64700.0,33400.0,133000.0,HASS
21,Film,37900.0,68500.0,33900.0,136000.0,HASS
22,Finance,47900.0,88300.0,47200.0,195000.0,Business
23,Forestry,39100.0,62600.0,41000.0,111000.0,Business
24,Geography,41200.0,65500.0,40000.0,132000.0,HASS
25,Geology,43500.0,79500.0,45000.0,156000.0,STEM
26,Graphic Design,35700.0,59800.0,36000.0,112000.0,HASS
27,Health Care Administration,38800.0,60600.0,34600.0,101000.0,Business
28,History,39200.0,71000.0,37000.0,149000.0,HASS
29,Hospitality & Tourism,37800.0,57500.0,35500.0,124000.0,Business
30,Industrial Engineering,57700.0,94700.0,57100.0,173000.0,STEM
31,Information Technology (IT),49100.0,74800.0,44500.0,129000.0,STEM
32,Interior Design,36100.0,53200.0,35700.0,107000.0,HASS
33,International Relations,40900.0,80900.0,38200.0,157000.0,HASS
34,Journalism,35600.0,66700.0,38400.0,145000.0,HASS
35,Management Information Systems (MIS),49200.0,82300.0,45300.0,146000.0,STEM
36,Marketing,40800.0,79600.0,42100.0,175000.0,Business
37,Math,45400.0,92400.0,45200.0,183000.0,STEM
38,Mechanical Engineering,57900.0,93600.0,63700.0,163000.0,STEM
39,Music,35900.0,55000.0,26700.0,134000.0,HASS
40,Nursing,54200.0,67000.0,47600.0,98300.0,Business
41,Nutrition,39900.0,55300.0,33900.0,99200.0,HASS
42,Philosophy,39900.0,81200.0,35500.0,168000.0,HASS
43,Physician Assistant,74300.0,91700.0,66400.0,124000.0,STEM
44,Physics,50300.0,97300.0,56000.0,178000.0,STEM
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS

In [ ]:
clean_df['Undergraduate Major'][(clean_df['Mid-Career Median Salary'].idxmax())]

107000.0

In [ ]:
clean_df['Mid-Career Median Salary'].max()

107000.0

In [ ]:
clean_df['Undergraduate Major'][(clean_df['Starting Median Salary'].idxmin())]

'Spanish'

In [ ]:
clean_df['Undergraduate Major'][clean_df['Undergraduate Major'] == 'Spanish']

49    Spanish
Name: Undergraduate Major, dtype: object

In [ ]:
clean_df['Starting Median Salary'].min()

34000.0

# Challenge question 3

In [ ]:
clean_df['Undergraduate Major'][(clean_df['Mid-Career Median Salary'].idxmin())]

'Education'

In [ ]:
clean_df['Mid-Career 90th Percentile Salary'][clean_df['Undergraduate Major'] == 'Education']

18    102000.0
Name: Mid-Career 90th Percentile Salary, dtype: float64

Teachers should expect to earn this much :

In [ ]:
clean_df[clean_df['Undergraduate Major'] == 'Education']

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
18,Education,34900.0,52000.0,29300.0,102000.0,HASS

(another method)

In [ ]:
clean_df.loc[clean_df['Mid-Career Median Salary'].idxmin()]

Undergraduate Major                  Education
Starting Median Salary                 34900.0
Mid-Career Median Salary               52000.0
Mid-Career 10th Percentile Salary      29300.0
Mid-Career 90th Percentile Salary     102000.0
Group                                     HASS
Name: 18, dtype: object

In [ ]:
clean_df

In [ ]:
spread_col = clean_df['Mid-Career 90th Percentile Salary'].subtract(clean_df['Mid-Career 10th Percentile Salary'])

In [ ]:
sorted_df = clean_df.sort_values('Spread')

In [ ]:
sorted_df[['Undergraduate Major', 'Spread']].head()

# Challenge part 8

In [ ]:
myDf = clean_df.sort_values('Mid-Career 90th Percentile Salary' ,ascending=False)

In [ ]:
myDf[['Undergraduate Major', 'Mid-Career 90th Percentile Salary']].head()

     Undergraduate Major  Mid-Career 90th Percentile Salary
17             Economics                           210000.0
22               Finance                           195000.0
8   Chemical Engineering                           194000.0
37                  Math                           183000.0
44               Physics                           178000.0

In [ ]:
clean_df.sort_values('Spread', ascending=False)[['Undergraduate Major', 'Spread']].head()

   Undergraduate Major    Spread
17           Economics  159400.0
22             Finance  147800.0
37                Math  137800.0
36           Marketing  132900.0
42          Philosophy  132500.0




---



# Part 9

---

In [ ]:
clean_df.groupby('Group').count()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary
Group,,,,,,
Business,12,12,12,12,12,12
HASS,22,22,22,22,22,22
STEM,16,16,16,16,16,16

In [ ]:
pd.options.display.float_format = '{:,.2f}'.format

In [ ]:
clean_df.groupby('Group').mean()

<ipython-input-57-61aa9b47bd8a>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  clean_df.groupby('Group').mean()

,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary
Group,,,,,
Business,"103,958.33","44,633.33","75,083.33","43,566.67","147,525.00"
HASS,"95,218.18","37,186.36","62,968.18","34,145.45","129,363.64"
STEM,"101,600.00","53,862.50","90,812.50","56,025.00","157,625.00"